// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace FIT_IoT.Server.Web.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migracija_v2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracija_v2));
        
        string IMigrationMetadata.Id
        {
            get { return "201801131310573_migracija_v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
